# Generated by Django 3.0.2 on 2020-03-07 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='项目名称')),
                ('desc', models.CharField(max_length=100, verbose_name='项目描述')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='请求类型')),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('url', models.CharField(max_length=100, unique=True, verbose_name='请求路由')),
                ('body', models.TextField(verbose_name='请求体')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mock.Project', verbose_name='关联项目')),
            ],
            options={
                'db_table': 'Api',
            },
        ),
    ]
